2019-07-16T06:01:10.0126954+01:00 0HLO9LAEU1UUC:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5507/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:01:10.7187500+01:00 0HLO9LAEU1UUC:00000001 [INF] Request finished in 837.8592ms 404  (791a596a)
2019-07-16T06:01:10.8291016+01:00  [INF] Connection id ""0HLO9LAEU1UUC"", Request id ""0HLO9LAEU1UUC:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:02:43.4072266+01:00 0HLO9LAEU1UUC:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5507/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:02:43.4140625+01:00 0HLO9LAEU1UUC:00000002 [INF] Request finished in 5.7767ms 404  (791a596a)
2019-07-16T06:02:43.4179688+01:00  [INF] Connection id ""0HLO9LAEU1UUC"", Request id ""0HLO9LAEU1UUC:00000002"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:03:59.1171875+01:00 0HLO9LAEU1UUC:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:5507/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:03:59.1513672+01:00 0HLO9LAEU1UUC:00000003 [INF] Request finished in 8.3867ms 404  (791a596a)
2019-07-16T06:03:59.1679688+01:00  [INF] Connection id ""0HLO9LAEU1UUC"", Request id ""0HLO9LAEU1UUC:00000003"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:04:06.0478516+01:00 0HLO9LAEU1UUC:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:5507/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:04:06.0527344+01:00 0HLO9LAEU1UUC:00000004 [INF] Request finished in 7.9348ms 404  (791a596a)
2019-07-16T06:04:06.0683594+01:00  [INF] Connection id ""0HLO9LAEU1UUC"", Request id ""0HLO9LAEU1UUC:00000004"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:04:43.4941407+01:00 0HLO9LAEU1UUC:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:04:43.5068360+01:00 0HLO9LAEU1UUC:00000005 [INF] Executing endpoint '"405 HTTP Method Not Supported"' (500cc934)
2019-07-16T06:04:43.5126954+01:00 0HLO9LAEU1UUC:00000005 [INF] Executed endpoint '"405 HTTP Method Not Supported"' (99874f2b)
2019-07-16T06:04:43.5273438+01:00 0HLO9LAEU1UUC:00000005 [INF] Request finished in 23.7785ms 405  (791a596a)
2019-07-16T06:04:43.5498047+01:00  [INF] Connection id ""0HLO9LAEU1UUC"", Request id ""0HLO9LAEU1UUC:00000005"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:04:48.3173829+01:00 0HLO9LAEU1UUC:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:04:48.3203125+01:00 0HLO9LAEU1UUC:00000006 [INF] Executing endpoint '"405 HTTP Method Not Supported"' (500cc934)
2019-07-16T06:04:48.3222657+01:00 0HLO9LAEU1UUC:00000006 [INF] Executed endpoint '"405 HTTP Method Not Supported"' (99874f2b)
2019-07-16T06:04:48.3417969+01:00 0HLO9LAEU1UUC:00000006 [INF] Request finished in 7.5741ms 405  (791a596a)
2019-07-16T06:04:48.3544922+01:00  [INF] Connection id ""0HLO9LAEU1UUC"", Request id ""0HLO9LAEU1UUC:00000006"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:05:12.9667969+01:00 0HLO9LAEU1UUC:00000007 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:05:12.9707032+01:00 0HLO9LAEU1UUC:00000007 [INF] Executing endpoint '"405 HTTP Method Not Supported"' (500cc934)
2019-07-16T06:05:12.9726563+01:00 0HLO9LAEU1UUC:00000007 [INF] Executed endpoint '"405 HTTP Method Not Supported"' (99874f2b)
2019-07-16T06:05:12.9941407+01:00 0HLO9LAEU1UUC:00000007 [INF] Request finished in 7.5643ms 405  (791a596a)
2019-07-16T06:05:13.0068360+01:00  [INF] Connection id ""0HLO9LAEU1UUC"", Request id ""0HLO9LAEU1UUC:00000007"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:05:41.7041016+01:00 0HLO9LCVS9C3C:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:05:42.3017579+01:00 0HLO9LCVS9C3C:00000001 [INF] Executing endpoint '"405 HTTP Method Not Supported"' (500cc934)
2019-07-16T06:05:42.3164063+01:00 0HLO9LCVS9C3C:00000001 [INF] Executed endpoint '"405 HTTP Method Not Supported"' (99874f2b)
2019-07-16T06:05:42.4511719+01:00 0HLO9LCVS9C3C:00000001 [INF] Request finished in 1064.8159ms 405  (791a596a)
2019-07-16T06:05:42.5097657+01:00  [INF] Connection id ""0HLO9LCVS9C3C"", Request id ""0HLO9LCVS9C3C:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:05:46.1103516+01:00 0HLO9LCVS9C3C:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:05:46.1132813+01:00 0HLO9LCVS9C3C:00000002 [INF] Executing endpoint '"405 HTTP Method Not Supported"' (500cc934)
2019-07-16T06:05:46.1162110+01:00 0HLO9LCVS9C3C:00000002 [INF] Executed endpoint '"405 HTTP Method Not Supported"' (99874f2b)
2019-07-16T06:05:46.1298829+01:00 0HLO9LCVS9C3C:00000002 [INF] Request finished in 9.0474ms 405  (791a596a)
2019-07-16T06:05:46.1445313+01:00  [INF] Connection id ""0HLO9LCVS9C3C"", Request id ""0HLO9LCVS9C3C:00000002"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:06:21.6171875+01:00 0HLO9LDBPLN8P:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:06:22.1337891+01:00 0HLO9LDBPLN8P:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:06:22.3017579+01:00 0HLO9LDBPLN8P:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:06:22.7021485+01:00 0HLO9LDBPLN8P:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 522.1373ms (afa2e885)
2019-07-16T06:06:22.7138672+01:00 0HLO9LDBPLN8P:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:06:22.7314454+01:00 0HLO9LDBPLN8P:00000001 [ERR] Connection id ""0HLO9LDBPLN8P"", Request id ""0HLO9LDBPLN8P:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:06:22.7587891+01:00 0HLO9LDBPLN8P:00000001 [INF] Request finished in 1531.4307ms 500 application/json (791a596a)
2019-07-16T06:06:22.8085938+01:00  [INF] Connection id ""0HLO9LDBPLN8P"", Request id ""0HLO9LDBPLN8P:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:06:26.5234375+01:00 0HLO9LDBPLN8R:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:06:26.5263672+01:00 0HLO9LDBPLN8R:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:06:26.5361329+01:00 0HLO9LDBPLN8R:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:06:26.5556641+01:00 0HLO9LDBPLN8R:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 3.9264ms (afa2e885)
2019-07-16T06:06:26.5683594+01:00 0HLO9LDBPLN8R:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:06:26.5742188+01:00 0HLO9LDBPLN8R:00000001 [ERR] Connection id ""0HLO9LDBPLN8R"", Request id ""0HLO9LDBPLN8R:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:06:26.5957032+01:00 0HLO9LDBPLN8R:00000001 [INF] Request finished in 76.7957ms 500 application/json (791a596a)
2019-07-16T06:06:26.6035157+01:00  [INF] Connection id ""0HLO9LDBPLN8R"", Request id ""0HLO9LDBPLN8R:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:08:47.9462891+01:00 0HLO9LENDR91M:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:08:48.4121094+01:00 0HLO9LENDR91M:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:08:48.5927735+01:00 0HLO9LENDR91M:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:08:48.8779297+01:00 0HLO9LENDR91M:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 255.4679ms (afa2e885)
2019-07-16T06:08:48.8828125+01:00 0HLO9LENDR91M:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:08:48.9052735+01:00 0HLO9LENDR91M:00000001 [ERR] Connection id ""0HLO9LENDR91M"", Request id ""0HLO9LENDR91M:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:08:48.9433594+01:00 0HLO9LENDR91M:00000001 [INF] Request finished in 1040.1877ms 500 application/json (791a596a)
2019-07-16T06:08:49.0019532+01:00  [INF] Connection id ""0HLO9LENDR91M"", Request id ""0HLO9LENDR91M:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:09:01.4375000+01:00 0HLO9LENDR91O:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 42 (ca22a1cb)
2019-07-16T06:09:01.4404297+01:00 0HLO9LENDR91O:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:09:01.4609375+01:00 0HLO9LENDR91O:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:09:01.4658204+01:00 0HLO9LENDR91O:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 3.3777ms (afa2e885)
2019-07-16T06:09:01.4687500+01:00 0HLO9LENDR91O:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:09:01.4726563+01:00 0HLO9LENDR91O:00000001 [ERR] Connection id ""0HLO9LENDR91O"", Request id ""0HLO9LENDR91O:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:09:01.4755860+01:00 0HLO9LENDR91O:00000001 [INF] Request finished in 66.5012ms 500 application/json (791a596a)
2019-07-16T06:09:01.4775391+01:00  [INF] Connection id ""0HLO9LENDR91O"", Request id ""0HLO9LENDR91O:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:09:14.4736329+01:00 0HLO9LENDR91Q:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:09:14.4755860+01:00 0HLO9LENDR91Q:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:09:14.4765625+01:00 0HLO9LENDR91Q:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:09:14.4814454+01:00 0HLO9LENDR91Q:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 2.2121ms (afa2e885)
2019-07-16T06:09:14.4843750+01:00 0HLO9LENDR91Q:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:09:14.4873047+01:00 0HLO9LENDR91Q:00000001 [ERR] Connection id ""0HLO9LENDR91Q"", Request id ""0HLO9LENDR91Q:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:09:14.4902344+01:00 0HLO9LENDR91Q:00000001 [INF] Request finished in 38.5852ms 500 application/json (791a596a)
2019-07-16T06:09:14.4921875+01:00  [INF] Connection id ""0HLO9LENDR91Q"", Request id ""0HLO9LENDR91Q:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:09:28.7792969+01:00 0HLO9LENDR91S:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:09:28.7890625+01:00 0HLO9LENDR91S:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:09:28.7910157+01:00 0HLO9LENDR91S:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:09:28.8203125+01:00 0HLO9LENDR91S:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 62.2857ms (afa2e885)
2019-07-16T06:09:28.8242188+01:00 0HLO9LENDR91S:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:09:28.8281250+01:00 0HLO9LENDR91S:00000001 [ERR] Connection id ""0HLO9LENDR91S"", Request id ""0HLO9LENDR91S:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:09:28.8330079+01:00 0HLO9LENDR91S:00000001 [INF] Request finished in 124.0785ms 500 application/json (791a596a)
2019-07-16T06:09:28.8378907+01:00  [INF] Connection id ""0HLO9LENDR91S"", Request id ""0HLO9LENDR91S:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:10:49.1132813+01:00 0HLO9LENDR91U:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:10:49.1240235+01:00 0HLO9LENDR91U:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:10:49.1269532+01:00 0HLO9LENDR91U:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:10:49.1640625+01:00 0HLO9LENDR91U:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 29.0697ms (afa2e885)
2019-07-16T06:10:49.1718750+01:00 0HLO9LENDR91U:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:10:49.1777344+01:00 0HLO9LENDR91U:00000001 [ERR] Connection id ""0HLO9LENDR91U"", Request id ""0HLO9LENDR91U:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:10:49.1796875+01:00 0HLO9LENDR91U:00000001 [INF] Request finished in 106.5785ms 500 application/json (791a596a)
2019-07-16T06:10:49.1826172+01:00  [INF] Connection id ""0HLO9LENDR91U"", Request id ""0HLO9LENDR91U:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:10:58.3242188+01:00 0HLO9LENDR920:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:10:58.3388672+01:00 0HLO9LENDR920:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:10:58.3417969+01:00 0HLO9LENDR920:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:10:58.3535157+01:00 0HLO9LENDR920:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 1.7147ms (afa2e885)
2019-07-16T06:10:58.3623047+01:00 0HLO9LENDR920:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:10:58.3671875+01:00 0HLO9LENDR920:00000001 [ERR] Connection id ""0HLO9LENDR920"", Request id ""0HLO9LENDR920:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:10:58.3710938+01:00 0HLO9LENDR920:00000001 [INF] Request finished in 59.9227ms 500 application/json (791a596a)
2019-07-16T06:10:58.3730469+01:00  [INF] Connection id ""0HLO9LENDR920"", Request id ""0HLO9LENDR920:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:16:33.9404297+01:00 0HLO9LJ284P37:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:16:34.5312500+01:00 0HLO9LJ284P37:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:16:34.6210938+01:00 0HLO9LJ284P37:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:16:34.8720704+01:00 0HLO9LJ284P37:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 238.4564ms (afa2e885)
2019-07-16T06:16:34.8828125+01:00 0HLO9LJ284P37:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:16:34.9199219+01:00 0HLO9LJ284P37:00000001 [ERR] Connection id ""0HLO9LJ284P37"", Request id ""0HLO9LJ284P37:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:16:34.9873047+01:00 0HLO9LJ284P37:00000001 [INF] Request finished in 1218.1676ms 500 application/json (791a596a)
2019-07-16T06:16:35.0507813+01:00  [INF] Connection id ""0HLO9LJ284P37"", Request id ""0HLO9LJ284P37:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:20:39.0898438+01:00 0HLO9LLBALGMC:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:20:39.5898438+01:00 0HLO9LLBALGMC:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:20:39.7451172+01:00 0HLO9LLBALGMC:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:20:40.0361329+01:00 0HLO9LLBALGMC:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 273.5564ms (afa2e885)
2019-07-16T06:20:40.0390625+01:00 0HLO9LLBALGMC:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:20:40.0732422+01:00 0HLO9LLBALGMC:00000001 [ERR] Connection id ""0HLO9LLBALGMC"", Request id ""0HLO9LLBALGMC:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.UsersController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T06:20:40.1152344+01:00 0HLO9LLBALGMC:00000001 [INF] Request finished in 1143.1161ms 500 application/json (791a596a)
2019-07-16T06:20:40.1660157+01:00  [INF] Connection id ""0HLO9LLBALGMC"", Request id ""0HLO9LLBALGMC:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T06:24:47.8515625+01:00 0HLO9LNLDQH1E:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:24:48.6103516+01:00 0HLO9LNLDQH1E:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:24:48.8691407+01:00 0HLO9LNLDQH1E:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:24:49.7587891+01:00 0HLO9LNLDQH1E:00000001 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:25:15.1523438+01:00 0HLO9LNLDQH1E:00000001 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 27106.9962ms. (50a9e262)
2019-07-16T06:25:15.2353516+01:00 0HLO9LNLDQH1E:00000001 [INF] Executing ObjectResult, writing value of type '"ChapelHill.models.User"'. (8a1b66c8)
2019-07-16T06:25:18.4326172+01:00 0HLO9LNLDQH1E:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 31590.8585ms (afa2e885)
2019-07-16T06:25:18.4472657+01:00 0HLO9LNLDQH1E:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:25:18.4648438+01:00 0HLO9LNLDQH1E:00000001 [INF] Request finished in 33260.3465ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T06:29:54.7460938+01:00 0HLO9LQGU0A00:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:29:55.2871094+01:00 0HLO9LQGU0A00:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:29:55.4726563+01:00 0HLO9LQGU0A00:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:29:56.3134766+01:00 0HLO9LQGU0A00:00000001 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:29:56.5029297+01:00 0HLO9LQGU0A00:00000001 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 176.1819ms. (50a9e262)
2019-07-16T06:29:56.5888672+01:00 0HLO9LQGU0A00:00000001 [INF] Executing ObjectResult, writing value of type '"ChapelHill.models.User"'. (8a1b66c8)
2019-07-16T06:29:56.8183594+01:00 0HLO9LQGU0A00:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 1333.3628ms (afa2e885)
2019-07-16T06:29:56.8222657+01:00 0HLO9LQGU0A00:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:29:56.8691407+01:00 0HLO9LQGU0A00:00000001 [INF] Request finished in 2217.7585ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T06:32:40.1103516+01:00 0HLO9LS25M8G3:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:32:40.7412110+01:00 0HLO9LS25M8G3:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:32:40.9218750+01:00 0HLO9LS25M8G3:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:32:41.8837891+01:00 0HLO9LS25M8G3:00000001 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:32:42.1181641+01:00 0HLO9LS25M8G3:00000001 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 229.0403ms. (50a9e262)
2019-07-16T06:32:42.2070313+01:00 0HLO9LS25M8G3:00000001 [INF] Executing ObjectResult, writing value of type '"ChapelHill.models.User"'. (8a1b66c8)
2019-07-16T06:32:42.4697266+01:00 0HLO9LS25M8G3:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 1709.1509ms (afa2e885)
2019-07-16T06:32:42.4736329+01:00 0HLO9LS25M8G3:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:32:42.5126954+01:00 0HLO9LS25M8G3:00000001 [INF] Request finished in 2725.8956ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T06:32:46.6933594+01:00 0HLO9LS25M8G3:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:32:46.6992188+01:00 0HLO9LS25M8G3:00000002 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:32:46.7070313+01:00 0HLO9LS25M8G3:00000002 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:32:46.7539063+01:00 0HLO9LS25M8G3:00000002 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:32:46.7705079+01:00 0HLO9LS25M8G3:00000002 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 0.2002ms. (50a9e262)
2019-07-16T06:32:46.7763672+01:00 0HLO9LS25M8G3:00000002 [INF] Executing ObjectResult, writing value of type '"ChapelHill.models.User"'. (8a1b66c8)
2019-07-16T06:32:46.7880860+01:00 0HLO9LS25M8G3:00000002 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 150.6494ms (afa2e885)
2019-07-16T06:32:46.7958985+01:00 0HLO9LS25M8G3:00000002 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:32:46.8076172+01:00 0HLO9LS25M8G3:00000002 [INF] Request finished in 221.7032ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T06:33:00.6630860+01:00 0HLO9LS25M8G3:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/Values/Get   (ca22a1cb)
2019-07-16T06:33:00.8173829+01:00 0HLO9LS25M8G3:00000003 [INF] Successfully validated the token. (60169667)
2019-07-16T06:33:00.8408204+01:00 0HLO9LS25M8G3:00000003 [INF] Executing endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (500cc934)
2019-07-16T06:33:00.8544922+01:00 0HLO9LS25M8G3:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing controller action with signature "System.String Get(Int32)" on controller "ChapelHill.Controllers.ValuesController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:33:00.8994141+01:00 0HLO9LS25M8G3:00000003 [INF] Authorization was successful. (0d575a54)
2019-07-16T06:33:00.9794922+01:00 0HLO9LS25M8G3:00000003 [INF] Executing action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" - Validation state: Invalid (dad538d7)
2019-07-16T06:33:00.9843750+01:00 0HLO9LS25M8G3:00000003 [INF] Executed action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 2.8566ms. (50a9e262)
2019-07-16T06:33:00.9902344+01:00 0HLO9LS25M8G3:00000003 [INF] Executing ObjectResult, writing value of type '"System.String"'. (8a1b66c8)
2019-07-16T06:33:01.0253907+01:00 0HLO9LS25M8G3:00000003 [INF] Executed action "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" in 202.3998ms (afa2e885)
2019-07-16T06:33:01.0273438+01:00 0HLO9LS25M8G3:00000003 [INF] Executed endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (99874f2b)
2019-07-16T06:33:01.0302735+01:00 0HLO9LS25M8G3:00000003 [INF] Request finished in 497.1616ms 200 text/plain; charset=utf-8 (791a596a)
2019-07-16T06:35:27.4121094+01:00 0HLO9LTK2E1IJ:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T06:35:28.0322266+01:00 0HLO9LTK2E1IJ:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T06:35:28.2529297+01:00 0HLO9LTK2E1IJ:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:35:28.9238282+01:00 0HLO9LTK2E1IJ:00000001 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:35:29.1386719+01:00 0HLO9LTK2E1IJ:00000001 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 200.9897ms. (50a9e262)
2019-07-16T06:35:29.2343750+01:00 0HLO9LTK2E1IJ:00000001 [INF] Executing ObjectResult, writing value of type '"ChapelHill.models.User"'. (8a1b66c8)
2019-07-16T06:35:29.5117188+01:00 0HLO9LTK2E1IJ:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 1302.1924ms (afa2e885)
2019-07-16T06:35:29.5175782+01:00 0HLO9LTK2E1IJ:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T06:35:29.5869141+01:00 0HLO9LTK2E1IJ:00000001 [INF] Request finished in 2615.4236ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T06:35:46.9345704+01:00 0HLO9LTK2E1IJ:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/Values/   (ca22a1cb)
2019-07-16T06:35:47.0234375+01:00 0HLO9LTK2E1IJ:00000002 [INF] Successfully validated the token. (60169667)
2019-07-16T06:35:47.0332032+01:00 0HLO9LTK2E1IJ:00000002 [INF] Executing endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (500cc934)
2019-07-16T06:35:47.0371094+01:00 0HLO9LTK2E1IJ:00000002 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing controller action with signature "System.Collections.Generic.IEnumerable`1[System.String] Get()" on controller "ChapelHill.Controllers.ValuesController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:35:47.0917969+01:00 0HLO9LTK2E1IJ:00000002 [INF] Authorization was successful. (0d575a54)
2019-07-16T06:35:47.1093750+01:00 0HLO9LTK2E1IJ:00000002 [INF] Executing action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:35:47.1142579+01:00 0HLO9LTK2E1IJ:00000002 [INF] Executed action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 2.9321ms. (50a9e262)
2019-07-16T06:35:47.1220704+01:00 0HLO9LTK2E1IJ:00000002 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-07-16T06:35:47.1494141+01:00 0HLO9LTK2E1IJ:00000002 [INF] Executed action "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" in 143.6264ms (afa2e885)
2019-07-16T06:35:47.1503907+01:00 0HLO9LTK2E1IJ:00000002 [INF] Executed endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (99874f2b)
2019-07-16T06:35:47.1611329+01:00 0HLO9LTK2E1IJ:00000002 [INF] Request finished in 257.6948ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T06:35:58.9453125+01:00 0HLO9LTK2E1IJ:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/Values/   (ca22a1cb)
2019-07-16T06:35:58.9482422+01:00 0HLO9LTK2E1IJ:00000003 [INF] Executing endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (500cc934)
2019-07-16T06:35:58.9560547+01:00 0HLO9LTK2E1IJ:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing controller action with signature "System.Collections.Generic.IEnumerable`1[System.String] Get()" on controller "ChapelHill.Controllers.ValuesController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:35:58.9599610+01:00 0HLO9LTK2E1IJ:00000003 [INF] Authorization failed. (b15dd539)
2019-07-16T06:35:58.9638672+01:00 0HLO9LTK2E1IJ:00000003 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-07-16T06:35:58.9921875+01:00 0HLO9LTK2E1IJ:00000003 [INF] Executing ChallengeResult with authentication schemes (["Bearer"]). (f3dca807)
2019-07-16T06:35:59.0380860+01:00 0HLO9LTK2E1IJ:00000003 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-07-16T06:35:59.0390625+01:00 0HLO9LTK2E1IJ:00000003 [INF] Executed action "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" in 85.7402ms (afa2e885)
2019-07-16T06:35:59.0419922+01:00 0HLO9LTK2E1IJ:00000003 [INF] Executed endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (99874f2b)
2019-07-16T06:35:59.0527344+01:00 0HLO9LTK2E1IJ:00000003 [INF] Request finished in 115.0008ms 401  (791a596a)
2019-07-16T06:36:07.9921875+01:00 0HLO9LTK2E1IJ:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/Values/   (ca22a1cb)
2019-07-16T06:36:08.0000000+01:00 0HLO9LTK2E1IJ:00000004 [INF] Successfully validated the token. (60169667)
2019-07-16T06:36:08.0029297+01:00 0HLO9LTK2E1IJ:00000004 [INF] Executing endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (500cc934)
2019-07-16T06:36:08.0166016+01:00 0HLO9LTK2E1IJ:00000004 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing controller action with signature "System.Collections.Generic.IEnumerable`1[System.String] Get()" on controller "ChapelHill.Controllers.ValuesController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:36:08.0312500+01:00 0HLO9LTK2E1IJ:00000004 [INF] Authorization was successful. (0d575a54)
2019-07-16T06:36:08.0449219+01:00 0HLO9LTK2E1IJ:00000004 [INF] Executing action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:36:08.0488282+01:00 0HLO9LTK2E1IJ:00000004 [INF] Executed action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 0.0501ms. (50a9e262)
2019-07-16T06:36:08.0517579+01:00 0HLO9LTK2E1IJ:00000004 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-07-16T06:36:08.0585938+01:00 0HLO9LTK2E1IJ:00000004 [INF] Executed action "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" in 51.9634ms (afa2e885)
2019-07-16T06:36:08.0625000+01:00 0HLO9LTK2E1IJ:00000004 [INF] Executed endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (99874f2b)
2019-07-16T06:36:08.0664063+01:00 0HLO9LTK2E1IJ:00000004 [INF] Request finished in 153.808ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T06:59:56.1767579+01:00 0HLO9MB9PGV9J:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/Values/   (ca22a1cb)
2019-07-16T06:59:56.8808594+01:00 0HLO9MB9PGV9J:00000001 [INF] Successfully validated the token. (60169667)
2019-07-16T06:59:57.1367188+01:00 0HLO9MB9PGV9J:00000001 [INF] Executing endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (500cc934)
2019-07-16T06:59:57.2656250+01:00 0HLO9MB9PGV9J:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing controller action with signature "System.Collections.Generic.IEnumerable`1[System.String] Get()" on controller "ChapelHill.Controllers.ValuesController" ("ChapelHill"). (122b2fdf)
2019-07-16T06:59:57.3525391+01:00 0HLO9MB9PGV9J:00000001 [INF] Authorization was successful. (0d575a54)
2019-07-16T06:59:57.4423829+01:00 0HLO9MB9PGV9J:00000001 [INF] Executing action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T06:59:57.4580079+01:00 0HLO9MB9PGV9J:00000001 [INF] Executed action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 4.139ms. (50a9e262)
2019-07-16T06:59:57.5468750+01:00 0HLO9MB9PGV9J:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-07-16T06:59:57.8310547+01:00 0HLO9MB9PGV9J:00000001 [INF] Executed action "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" in 565.8799ms (afa2e885)
2019-07-16T06:59:57.8349610+01:00 0HLO9MB9PGV9J:00000001 [INF] Executed endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (99874f2b)
2019-07-16T06:59:57.8789063+01:00 0HLO9MB9PGV9J:00000001 [INF] Request finished in 1824.993ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T07:00:01.3408204+01:00 0HLO9MB9PGV9J:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/Values/   (ca22a1cb)
2019-07-16T07:00:01.3466797+01:00 0HLO9MB9PGV9J:00000002 [INF] Successfully validated the token. (60169667)
2019-07-16T07:00:01.3554688+01:00 0HLO9MB9PGV9J:00000002 [INF] Executing endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (500cc934)
2019-07-16T07:00:01.3671875+01:00 0HLO9MB9PGV9J:00000002 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing controller action with signature "System.Collections.Generic.IEnumerable`1[System.String] Get()" on controller "ChapelHill.Controllers.ValuesController" ("ChapelHill"). (122b2fdf)
2019-07-16T07:00:01.3701172+01:00 0HLO9MB9PGV9J:00000002 [INF] Authorization was successful. (0d575a54)
2019-07-16T07:00:01.3906250+01:00 0HLO9MB9PGV9J:00000002 [INF] Executing action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T07:00:01.3925782+01:00 0HLO9MB9PGV9J:00000002 [INF] Executed action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 0.0288ms. (50a9e262)
2019-07-16T07:00:01.3964844+01:00 0HLO9MB9PGV9J:00000002 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-07-16T07:00:01.3994141+01:00 0HLO9MB9PGV9J:00000002 [INF] Executed action "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" in 59.7213ms (afa2e885)
2019-07-16T07:00:01.4033204+01:00 0HLO9MB9PGV9J:00000002 [INF] Executed endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (99874f2b)
2019-07-16T07:00:01.4169922+01:00 0HLO9MB9PGV9J:00000002 [INF] Request finished in 95.1729ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T07:00:08.8535157+01:00 0HLO9MB9PGV9J:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 50 (ca22a1cb)
2019-07-16T07:00:08.8564454+01:00 0HLO9MB9PGV9J:00000003 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T07:00:08.9062500+01:00 0HLO9MB9PGV9J:00000003 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T07:00:09.3271485+01:00 0HLO9MB9PGV9J:00000003 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T07:00:09.3359375+01:00 0HLO9MB9PGV9J:00000003 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.BadRequestObjectResult" in 6.9925ms. (50a9e262)
2019-07-16T07:00:09.3388672+01:00 0HLO9MB9PGV9J:00000003 [INF] Executing ObjectResult, writing value of type '"<>f__AnonymousType0`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]"'. (8a1b66c8)
2019-07-16T07:00:09.4033204+01:00 0HLO9MB9PGV9J:00000003 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 582.7299ms (afa2e885)
2019-07-16T07:00:09.4072266+01:00 0HLO9MB9PGV9J:00000003 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T07:00:09.4130860+01:00 0HLO9MB9PGV9J:00000003 [INF] Request finished in 647.0872ms 400 application/json; charset=utf-8 (791a596a)
2019-07-16T07:00:49.0751954+01:00 0HLO9MB9PGV9J:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 72 (ca22a1cb)
2019-07-16T07:00:49.0781250+01:00 0HLO9MB9PGV9J:00000004 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T07:00:49.0810547+01:00 0HLO9MB9PGV9J:00000004 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T07:00:49.0830079+01:00 0HLO9MB9PGV9J:00000004 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T07:00:49.1259766+01:00 0HLO9MB9PGV9J:00000004 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 40.8099ms. (50a9e262)
2019-07-16T07:00:49.1308594+01:00 0HLO9MB9PGV9J:00000004 [INF] Executing ObjectResult, writing value of type '"ChapelHill.models.User"'. (8a1b66c8)
2019-07-16T07:00:49.1455079+01:00 0HLO9MB9PGV9J:00000004 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 59.0877ms (afa2e885)
2019-07-16T07:00:49.1650391+01:00 0HLO9MB9PGV9J:00000004 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T07:00:49.1679688+01:00 0HLO9MB9PGV9J:00000004 [INF] Request finished in 156.159ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T07:01:10.2519532+01:00 0HLO9MB9PGV9J:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:5507/api/Values/   (ca22a1cb)
2019-07-16T07:01:10.2705079+01:00 0HLO9MB9PGV9J:00000005 [INF] Successfully validated the token. (60169667)
2019-07-16T07:01:10.2773438+01:00 0HLO9MB9PGV9J:00000005 [INF] Executing endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (500cc934)
2019-07-16T07:01:10.2832032+01:00 0HLO9MB9PGV9J:00000005 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing controller action with signature "System.Collections.Generic.IEnumerable`1[System.String] Get()" on controller "ChapelHill.Controllers.ValuesController" ("ChapelHill"). (122b2fdf)
2019-07-16T07:01:10.2861329+01:00 0HLO9MB9PGV9J:00000005 [INF] Authorization was successful. (0d575a54)
2019-07-16T07:01:10.2890625+01:00 0HLO9MB9PGV9J:00000005 [INF] Executing action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T07:01:10.2919922+01:00 0HLO9MB9PGV9J:00000005 [INF] Executed action method "ChapelHill.Controllers.ValuesController.Get (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 0.0076ms. (50a9e262)
2019-07-16T07:01:10.2949219+01:00 0HLO9MB9PGV9J:00000005 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-07-16T07:01:10.3027344+01:00 0HLO9MB9PGV9J:00000005 [INF] Executed action "ChapelHill.Controllers.ValuesController.Get (ChapelHill)" in 11.2923ms (afa2e885)
2019-07-16T07:01:10.3056641+01:00 0HLO9MB9PGV9J:00000005 [INF] Executed endpoint '"ChapelHill.Controllers.ValuesController.Get (ChapelHill)"' (99874f2b)
2019-07-16T07:01:10.3125000+01:00 0HLO9MB9PGV9J:00000005 [INF] Request finished in 57.2927ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T11:17:32.3701172+01:00 0HLO9QR81B5F1:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:17:32.9941407+01:00 0HLO9QR81B5F1:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:17:33.1855469+01:00 0HLO9QR81B5F1:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:17:33.4267579+01:00 0HLO9QR81B5F1:00000001 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 236.4003ms (afa2e885)
2019-07-16T11:17:33.4296875+01:00 0HLO9QR81B5F1:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T11:17:33.4433594+01:00 0HLO9QR81B5F1:00000001 [ERR] Connection id ""0HLO9QR81B5F1"", Request id ""0HLO9QR81B5F1:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.DIServerController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T11:17:33.4726563+01:00 0HLO9QR81B5F1:00000001 [INF] Request finished in 1286.6665ms 500 application/json (791a596a)
2019-07-16T11:17:33.5214844+01:00  [INF] Connection id ""0HLO9QR81B5F1"", Request id ""0HLO9QR81B5F1:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T11:18:04.5537110+01:00 0HLO9QR81B5F3:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:18:04.5556641+01:00 0HLO9QR81B5F3:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:18:04.5615235+01:00 0HLO9QR81B5F3:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:18:04.5703125+01:00 0HLO9QR81B5F3:00000001 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 5.7954ms (afa2e885)
2019-07-16T11:18:04.5732422+01:00 0HLO9QR81B5F3:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T11:18:04.5771485+01:00 0HLO9QR81B5F3:00000001 [ERR] Connection id ""0HLO9QR81B5F3"", Request id ""0HLO9QR81B5F3:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'SAPAPI.Controllers.DIServerController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T11:18:04.5791016+01:00 0HLO9QR81B5F3:00000001 [INF] Request finished in 27.0659ms 500 application/json (791a596a)
2019-07-16T11:18:04.5839844+01:00  [INF] Connection id ""0HLO9QR81B5F3"", Request id ""0HLO9QR81B5F3:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T11:20:09.5234375+01:00 0HLO9QSMUB8QG:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:20:10.0439454+01:00 0HLO9QSMUB8QG:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:20:10.2197266+01:00 0HLO9QSMUB8QG:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:20:10.4375000+01:00 0HLO9QSMUB8QG:00000001 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 197.519ms (afa2e885)
2019-07-16T11:20:10.4433594+01:00 0HLO9QSMUB8QG:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T11:20:10.4570313+01:00 0HLO9QSMUB8QG:00000001 [ERR] Connection id ""0HLO9QSMUB8QG"", Request id ""0HLO9QSMUB8QG:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'AutoMapper.IMapper' while attempting to activate 'SAPAPI.Controllers.DIServerController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__185`1.MoveNext()
2019-07-16T11:20:10.4912110+01:00 0HLO9QSMUB8QG:00000001 [INF] Request finished in 1027.5222ms 500 application/json (791a596a)
2019-07-16T11:20:10.5419922+01:00  [INF] Connection id ""0HLO9QSMUB8QG"", Request id ""0HLO9QSMUB8QG:00000001"": the application completed without reading the entire request body. (54ac9468)
2019-07-16T11:21:02.7158204+01:00 0HLO9QT6R6LCR:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:21:03.2060547+01:00 0HLO9QT6R6LCR:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:21:03.3623047+01:00 0HLO9QT6R6LCR:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:21:03.5615235+01:00 0HLO9QT6R6LCR:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:22:40.3583985+01:00 0HLO9QU3S7LLN:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:22:40.8837891+01:00 0HLO9QU3S7LLN:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:22:41.0673829+01:00 0HLO9QU3S7LLN:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:22:41.3486329+01:00 0HLO9QU3S7LLN:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:23:23.2753907+01:00 0HLO9QU3S7LLP:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/plain 1106 (ca22a1cb)
2019-07-16T11:23:23.2919922+01:00 0HLO9QU3S7LLP:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:23:37.2441407+01:00 0HLO9QUKQSSK5:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/plain 1106 (ca22a1cb)
2019-07-16T11:23:37.7832032+01:00 0HLO9QUKQSSK5:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:23:37.9716797+01:00 0HLO9QUKQSSK5:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:23:38.1904297+01:00 0HLO9QUKQSSK5:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:25:34.4130860+01:00 0HLO9QVNO28L0:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact application/xml 1106 (ca22a1cb)
2019-07-16T11:25:34.9140625+01:00 0HLO9QVNO28L0:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:25:35.4462891+01:00 0HLO9QVNO28L0:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.Xml.XmlDocument)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:25:35.7050782+01:00 0HLO9QVNO28L0:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:27:08.7529297+01:00 0HLO9R0JSACCN:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact application/xml 1106 (ca22a1cb)
2019-07-16T11:27:09.2529297+01:00 0HLO9R0JSACCN:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:27:09.4072266+01:00 0HLO9R0JSACCN:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:27:09.6162110+01:00 0HLO9R0JSACCN:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:28:13.4541016+01:00 0HLO9R0JSACCP:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:28:13.4570313+01:00 0HLO9R0JSACCP:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:28:13.4648438+01:00 0HLO9R0JSACCP:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:28:13.4697266+01:00 0HLO9R0JSACCP:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:42:13.9960938+01:00 0HLO9R91L1B8Q:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:42:14.5156250+01:00 0HLO9R91L1B8Q:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:42:14.6875000+01:00 0HLO9R91L1B8Q:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.String)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:42:14.9716797+01:00 0HLO9R91L1B8Q:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:43:34.6113282+01:00 0HLO9R9PM4MJ5:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:43:35.2216797+01:00 0HLO9R9PM4MJ5:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:43:35.3984375+01:00 0HLO9R9PM4MJ5:00000001 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.Xml.Linq.XElement)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:43:36.4111329+01:00 0HLO9R9PM4MJ5:00000001 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:44:44.8466797+01:00 0HLO9R9PM4MJ5:00000001 [INF] Executed action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 69744.1335ms. (50a9e262)
2019-07-16T11:44:44.9189454+01:00 0HLO9R9PM4MJ5:00000001 [INF] Executing ObjectResult, writing value of type '"System.Xml.XmlDocument"'. (8a1b66c8)
2019-07-16T11:44:45.2968750+01:00 0HLO9R9PM4MJ5:00000001 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 71274.7515ms (afa2e885)
2019-07-16T11:44:45.3046875+01:00 0HLO9R9PM4MJ5:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T11:44:45.4169922+01:00 0HLO9R9PM4MJ5:00000001 [INF] Request finished in 72256.0663ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T11:49:25.0615235+01:00 0HLO9R9PM4MJ5:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 1106 (ca22a1cb)
2019-07-16T11:49:25.0625000+01:00 0HLO9R9PM4MJ5:00000002 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:49:25.0654297+01:00 0HLO9R9PM4MJ5:00000002 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.Xml.Linq.XElement)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:49:25.0673829+01:00 0HLO9R9PM4MJ5:00000002 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:49:33.9716797+01:00 0HLO9R9PM4MJ5:00000002 [INF] Executed action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 9221.3746ms. (50a9e262)
2019-07-16T11:49:33.9746094+01:00 0HLO9R9PM4MJ5:00000002 [INF] Executing ObjectResult, writing value of type '"System.Xml.XmlDocument"'. (8a1b66c8)
2019-07-16T11:49:33.9824219+01:00 0HLO9R9PM4MJ5:00000002 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 9234.7307ms (afa2e885)
2019-07-16T11:49:33.9833985+01:00 0HLO9R9PM4MJ5:00000002 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T11:49:34.0205079+01:00 0HLO9R9PM4MJ5:00000002 [INF] Request finished in 9249.9457ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T11:51:23.7343750+01:00 0HLO9R9PM4MJ5:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 706 (ca22a1cb)
2019-07-16T11:51:23.7373047+01:00 0HLO9R9PM4MJ5:00000003 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T11:51:23.7392579+01:00 0HLO9R9PM4MJ5:00000003 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.Xml.Linq.XElement)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T11:51:23.7509766+01:00 0HLO9R9PM4MJ5:00000003 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T11:52:53.6445313+01:00 0HLO9R9PM4MJ5:00000003 [INF] Executed action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 111193.7688ms. (50a9e262)
2019-07-16T11:52:53.6591797+01:00 0HLO9R9PM4MJ5:00000003 [INF] Executing ObjectResult, writing value of type '"System.Xml.XmlDocument"'. (8a1b66c8)
2019-07-16T11:52:53.6787110+01:00 0HLO9R9PM4MJ5:00000003 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 111263.1769ms (afa2e885)
2019-07-16T11:52:53.6855469+01:00 0HLO9R9PM4MJ5:00000003 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T11:52:53.7216797+01:00 0HLO9R9PM4MJ5:00000003 [INF] Request finished in 111342.4793ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T12:01:08.7314454+01:00 0HLO9R9PM4MJ5:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 706 (ca22a1cb)
2019-07-16T12:01:08.7333985+01:00 0HLO9R9PM4MJ5:00000004 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T12:01:08.7373047+01:00 0HLO9R9PM4MJ5:00000004 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.Xml.Linq.XElement)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T12:01:08.7382813+01:00 0HLO9R9PM4MJ5:00000004 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T12:01:14.3759766+01:00 0HLO9R9PM4MJ5:00000004 [INF] Executed action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 5689.8584ms. (50a9e262)
2019-07-16T12:01:14.3789063+01:00 0HLO9R9PM4MJ5:00000004 [INF] Executing ObjectResult, writing value of type '"System.Xml.XmlDocument"'. (8a1b66c8)
2019-07-16T12:01:14.3798829+01:00 0HLO9R9PM4MJ5:00000004 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 5697.773ms (afa2e885)
2019-07-16T12:01:14.3828125+01:00 0HLO9R9PM4MJ5:00000004 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T12:01:14.3847657+01:00 0HLO9R9PM4MJ5:00000004 [INF] Request finished in 5727.3961ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T12:11:18.1933594+01:00 0HLO9RP9FVD1O:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/users/authenticate application/json 72 (ca22a1cb)
2019-07-16T12:11:18.6689454+01:00 0HLO9RP9FVD1O:00000001 [INF] Executing endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (500cc934)
2019-07-16T12:11:18.7441407+01:00 0HLO9RP9FVD1O:00000001 [INF] Route matched with "{action = \"Authenticate\", controller = \"Users\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Authenticate(ChapelHill.models.User)" on controller "SAPAPI.Controllers.UsersController" ("ChapelHill"). (122b2fdf)
2019-07-16T12:11:19.4013672+01:00 0HLO9RP9FVD1O:00000001 [INF] Executing action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T12:11:19.6904297+01:00 0HLO9RP9FVD1O:00000001 [INF] Executed action method "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 285.4495ms. (50a9e262)
2019-07-16T12:11:19.7597657+01:00 0HLO9RP9FVD1O:00000001 [INF] Executing ObjectResult, writing value of type '"ChapelHill.models.User"'. (8a1b66c8)
2019-07-16T12:11:19.9384766+01:00 0HLO9RP9FVD1O:00000001 [INF] Executed action "SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)" in 1187.392ms (afa2e885)
2019-07-16T12:11:19.9433594+01:00 0HLO9RP9FVD1O:00000001 [INF] Executed endpoint '"SAPAPI.Controllers.UsersController.Authenticate (ChapelHill)"' (99874f2b)
2019-07-16T12:11:19.9765625+01:00 0HLO9RP9FVD1O:00000001 [INF] Request finished in 1876.4675ms 200 application/json; charset=utf-8 (791a596a)
2019-07-16T12:13:07.1601563+01:00 0HLO9RP9FVD1O:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:5507/api/DIServer/Interact text/xml 703 (ca22a1cb)
2019-07-16T12:13:07.1650391+01:00 0HLO9RP9FVD1O:00000002 [INF] Executing endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (500cc934)
2019-07-16T12:13:07.1728516+01:00 0HLO9RP9FVD1O:00000002 [INF] Route matched with "{action = \"Interact\", controller = \"DIServer\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Interact(System.Xml.Linq.XElement)" on controller "SAPAPI.Controllers.DIServerController" ("ChapelHill"). (122b2fdf)
2019-07-16T12:13:07.4130860+01:00 0HLO9RP9FVD1O:00000002 [INF] Executing action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" - Validation state: Valid (dad538d7)
2019-07-16T12:13:13.1132813+01:00 0HLO9RP9FVD1O:00000002 [INF] Executed action method "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 5932.7739ms. (50a9e262)
2019-07-16T12:13:13.1162110+01:00 0HLO9RP9FVD1O:00000002 [INF] Executing ObjectResult, writing value of type '"System.Xml.XmlDocument"'. (8a1b66c8)
2019-07-16T12:13:13.1748047+01:00 0HLO9RP9FVD1O:00000002 [INF] Executed action "SAPAPI.Controllers.DIServerController.Interact (ChapelHill)" in 6286.7803ms (afa2e885)
2019-07-16T12:13:13.1787110+01:00 0HLO9RP9FVD1O:00000002 [INF] Executed endpoint '"SAPAPI.Controllers.DIServerController.Interact (ChapelHill)"' (99874f2b)
2019-07-16T12:13:13.1816407+01:00 0HLO9RP9FVD1O:00000002 [INF] Request finished in 6319.0548ms 200 application/json; charset=utf-8 (791a596a)
